### ISSUE TITLE
For simple mod, it seems to do alot

### ISSUE THREAD

**Issue by Zaflis** [MrIbby/EnderCompass#1]
https://www.dropbox.com/s/9q5qri919r3b0g2/endercompass_opis.jpg?dl=0

In opis view, this mod is using over half of what AE2 does for server tps (not counting tile entities), even though we are talking about very tiny numbers. Server does not lag because of this, i think. Compared to all those mods, and that there are no players on server at the time of image that would have the compass in the inventory.

To put in more perspective, I have hundreds of items being transported by AE system each second. Many autocrafting queues more than 20 RF-powered machines in the base... 1 compass compares to processing required to all of them? :p

**Comment by MrIbby** [comment]
I haven't been working with Ender Compass lately, but that seems to be a problem that should be fixed ASAP :P I'm guessing the mod sends a packet of the stronghold position each tick.

**Comment by Zaflis** [comment]
Balance is fine i guess. It may not normally take even those 5 ender pearls to find the stronghold, since most of them can be recollected back when thrown.

**Comment by MrIbby** [comment]
Could you test this?: https://copy.com/GIHrnqUio76LlATK/EnderCompass-1.7.10-1.1-SNAPSHOT.jar

**Comment by Zaflis** [comment]
Well.. i'm used to always kill the dragon before wither so... i'd skip the compass if it needed a star :p Maybe iron blocks in the corners, redstone middle?

// Who set us up the TNT?
http://pastebin.com/CaUw01FB

**Comment by MrIbby** [comment]
Oops, this should work: https://copy.com/GIHrnqUio76LlATK/EnderCompass-1.7.10-1.1-SNAPSHOT.jar

**Comment by Zaflis** [comment]
It's working now, and timing is 0 microseconds.

Diamonds? :)   Emeralds are perhaps even too rare, but still also a valid option for recipe.

**Comment by MrIbby** [comment]
Since this is fixed, I'll close the issue and move discussion about balancing to #2
