### ISSUE TITLE
Pointing towards stronghold from NEI

### ISSUE THREAD

**Issue by Zaflis** [MrIbby/EnderCompass#3]
This is a bit of a cheat, that we can see stronghold location before crafting it.

How other mods work around it? One example is AE2's meteorite compass which keeps spinning around when looked at in NEI. You could also set it to point for example north always, unless it's in player inventory.

**Comment by MrIbby** [comment]
Which version of AE2 has the meteorite compass?

**Comment by MrIbby** [comment]
Thanks! Expect an update in a few days =)

**Comment by MrIbby** [comment]
Should this be configurable?

**Comment by Zaflis** [comment]
I don't think so, cheat is a cheat :)

**Comment by MrIbby** [comment]
Hm... There doesn't appear to be an efficient way to do this. For example, AE2's compass doesn't render normally in a chest, even if it is open.

**Comment by Zaflis** [comment]
At least it's not pointing towards stronghold from NEI now, but it doesn't point there from anywhere else either :p

Posted here more details: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2220888-mribbys-mods-ender-compass-better-ore-fortune#c11

**Comment by MrIbby** [comment]
Leave a comment if you need this in a specific Minecraft version.
