### ISSUE TITLE
Ender Compass does not work in Multiplayer

### ISSUE THREAD

**Issue by blay09** [MrIbby/EnderCompass#4]
https://github.com/MrIbby/EnderCompass/blob/0749ba1a2ec7bbe242e706ade76cca4bc5067afe/src/main/java/com/outlook/siribby/endercompass/Proxy.java#L29

You're only sending the stronghold position to the first player who gets ticked as the position is no longer null afterwards and no further checks are being done (and thus no further sends).

Listen on the playerLogin event and send the position there too, so everyone gets it.

**Comment by Hund** [comment]
I guess we can safely assume this mod is abandonware. :/ I was looking forward on using this mod in my new world.

**Comment by MrIbby** [comment]
Yep, that's pretty much the situation. Although I'm not much interested in this mod anymore, the license allows other modder to pick it up and resume development, which reminds me that I need to change the license to something more international-friendly.

**Comment by MrIbby** [comment]
Try this: https://github.com/MrIbby/EnderCompass/releases/download/v1.2-SNAPSHOT/EnderCompass-1.7.10-1.2.jar

**Comment by Hund** [comment]
It works great! Thank you so much! :D

**Comment by MrIbby** [comment]
Hooray :tada:
d7af38e58c01d4e57f356ad0a037393d82fb9ac2
