### ISSUE TITLE
Scanning for Stronghold every tick when two players are in different dimensions

### ISSUE THREAD

**Issue by blay09** [MrIbby/EnderCompass#5]
If two players are in different dimensions on a server, the tick handler in Proxy.java will constantly switch currentWorld between the two worlds and keep searching the world for the Stronghold, switching the EnderCompass.strongholdPosition between the two.

That's unnecessary extra work for the server.

**Comment by MrIbby** [comment]
Okay so I rewrote the mod and added a packet that requests for the position of the stronghold. Here are the conditions that are required for a request to be sent: https://github.com/MrIbby/EnderCompass/blob/d7af38e58c01d4e57f356ad0a037393d82fb9ac2/src/main/java/com/outlook/siribby/endercompass/client/EnderCompassClient.java#L42-L49
