### ISSUE TITLE
Ender Compass won't point toward any strongholds

### ISSUE THREAD

**Issue by IndigoAvemour** [MrIbby/EnderCompass#7]
Screenshots here: http://imgur.com/a/2eqMa

No matter which orientation I face, the compass will not change. I'm not sure if this is a mere texture issue or what; the vanilla compass works perfectly fine, however. The mod is on version 1.8.9-1.2.2.

Any ideas what may be the issue? I think it could just be an issue on my end, since I play a custom modpack on 1.8.9 and I can only guess it could be one of the other mods messing it up.

**Comment by Hund** [comment]
I have the same issue.

* Minecraft 1.8.9
* Forge 12.16.1.1887
* Ender Compass 1.2.3

**Comment by MrIbby** [comment]
Try these:
* 1.8.9: https://www.dropbox.com/s/pgv505bxvbcwa4b/EnderCompass-1.8.x-1.2.2.1.jar?dl=0
* 1.9: https://www.dropbox.com/s/phvtlh29lqvou3q/EnderCompass-1.9.x-1.2.3.1.jar?dl=0
