### ISSUE TITLE
Enhancement: Port to 1.9.4

### ISSUE THREAD

**Issue by krelios** [MrIbby/EnderCompass#9]
Since so many mods are porting to 1.9.4, it would be nice to have a 1.9.4 version of this mod too.

**Comment by MrIbby** [comment]
Try this: https://www.dropbox.com/s/phvtlh29lqvou3q/EnderCompass-1.9.x-1.2.3.1.jar?dl=0

**Comment by krelios** [comment]
Works great! Thanks!
